name: deploy project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v7
      - name: install dependencies
        run: npm install
      - name: lint code
        run: npm run lint
      - name: test code
        run: npm run test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo 'deploying...'
      - name: context info
        run: echo "${{ github.workflow }}"
